# Generated by Django 4.2.7 on 2023-11-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_uid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Unique telegram chat id'),
        ),
    ]
