# Generated by Django 4.2.7 on 2023-11-06 18:23

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_uid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Unique telegram chat id'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default=0, max_length=150, unique=True, validators=[users.validators.TelegramNicknameValidator()], verbose_name='Unique telegram uid'),
            preserve_default=False,
        ),
    ]
