# Generated by Django 4.2.7 on 2023-11-21 08:54

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_telegram_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.TelegramNicknameValidator()], verbose_name='Unique telegram username'),
        ),
    ]
