# Generated by Django 4.2.7 on 2023-11-24 09:06

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_telegram_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[users.validators.TelegramNicknameValidator()], verbose_name='Unique telegram username'),
        ),
    ]
