# Generated by Django 4.2.7 on 2023-11-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place')),
                ('operation', models.CharField(max_length=200, verbose_name='Operation')),
                ('schedule', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'mon'), (2, 'tue'), (3, 'wed'), (4, 'thu'), (5, 'fri'), (6, 'sat'), (7, 'sun')], null=True, verbose_name='Habit schedule')),
                ('task_crontab', models.JSONField()),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Pleasant habit')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public habit')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='related habit')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
