# Generated by Django 4.2.7 on 2023-11-06 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place')),
                ('operation', models.CharField(max_length=200, verbose_name='Operation')),
                ('schedule', models.PositiveSmallIntegerField(choices=[(1, 'mon'), (2, 'tue'), (3, 'wed'), (4, 'thu'), (5, 'fri'), (6, 'sat'), (7, 'sun')], verbose_name='habit schedule')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Pleasant habit')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public habit')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='related habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
