# Generated by Django 4.2.7 on 2023-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_task_habit_task_crontab_alter_habit_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='task_crontab',
            field=models.JSONField(),
        ),
    ]
