# Generated by Django 4.2.7 on 2023-11-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0005_alter_habit_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='schedule',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'mon'), (2, 'tue'), (3, 'wed'), (4, 'thu'), (5, 'fri'), (6, 'sat'), (7, 'sun')], null=True, verbose_name='Habit schedule'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
