# Generated by Django 4.2.7 on 2023-11-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
        ('habits', '0006_alter_habit_schedule_alter_habit_user'),
    ]

    operations = [
    ]
